In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [18]:
url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet'
zones = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

In [19]:
df = pd.read_parquet(
    url
)
df_zones = pd.read_csv(
    zones
)

In [7]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [8]:
len(df)

46912

In [9]:
! uv add sql alchemy

Resolved 123 packages in 6.37s
Prepared 10 packages in 302ms
Uninstalled 3 packages in 23ms
░░░░░░░░░░░░░░░░░░░░ [0/10] Installing wheels...                                warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 10 packages in 204ms
 + alchemy==20.5
 + chardet==3.0.4
 + docutils==0.22.4
 + filelock==3.0.12
 - idna==3.13
 + idna==2.8
 + lockfile==0.12.2
 + python-daemon==2.2.4
 - requests==2.33.1
 + requests==2.22.0
 + sql==2022.4.0
 - urllib3==2.6.3
 + urllib3==1.25.11

In [10]:
from sqlalchemy import create_engine
engine =create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [11]:
df.head(0).to_sql(name='green_taxi_data', con=engine, if_exists='replace')

0

In [15]:
df.to_sql(name="green_taxi_data", con=engine, if_exists="append")

912

In [20]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [21]:
df_zones.head(0).to_sql(name='taxi_zones', con=engine, if_exists='replace')

0

In [22]:
df_zones.to_sql(name='taxi_zones', con=engine, if_exists="append")

265